# Generated by Django 5.1.7 on 2025-04-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_note_user_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
